org.openapitools.vertxweb.server.model.Order.StatusEnum.serializer=org.openapitools.vertxweb.server.model.Order.StatusEnum#serialize
org.openapitools.vertxweb.server.model.Order.StatusEnum.deserializer=org.openapitools.vertxweb.server.model.Order.StatusEnum#fromValue
org.openapitools.vertxweb.server.model.Pet.StatusEnum.serializer=org.openapitools.vertxweb.server.model.Pet.StatusEnum#serialize
org.openapitools.vertxweb.server.model.Pet.StatusEnum.deserializer=org.openapitools.vertxweb.server.model.Pet.StatusEnum#fromValue
java.time.LocalDate.serializer=org.openapitools.vertxweb.server.model.DataObjectMapper#serializeLocalDate
java.time.LocalDate.deserializer=java.time.LocalDate#parse
java.time.LocalDateTime.serializer=org.openapitools.vertxweb.server.model.DataObjectMapper#serializeLocalDateTime
java.time.LocalDateTime.deserializer=java.time.LocalDateTime#parse
java.time.OffsetDateTime.serializer=org.openapitools.vertxweb.server.model.DataObjectMapper#serializeOffsetDateTime
java.time.OffsetDateTime.deserializer=java.time.OffsetDateTime#parse
