org.openapitools.client.model.EnumArrays.JustSymbolEnum.serializer=org.openapitools.client.model.EnumArrays.JustSymbolEnum#serialize
org.openapitools.client.model.EnumArrays.JustSymbolEnum.deserializer=org.openapitools.client.model.EnumArrays.JustSymbolEnum#fromValue
org.openapitools.client.model.EnumClass.serializer=org.openapitools.client.model.EnumClass#serialize
org.openapitools.client.model.EnumClass.deserializer=org.openapitools.client.model.EnumClass#fromValue
org.openapitools.client.model.EnumTest.EnumStringEnum.serializer=org.openapitools.client.model.EnumTest.EnumStringEnum#serialize
org.openapitools.client.model.EnumTest.EnumStringEnum.deserializer=org.openapitools.client.model.EnumTest.EnumStringEnum#fromValue
org.openapitools.client.model.EnumTest.EnumStringRequiredEnum.serializer=org.openapitools.client.model.EnumTest.EnumStringRequiredEnum#serialize
org.openapitools.client.model.EnumTest.EnumStringRequiredEnum.deserializer=org.openapitools.client.model.EnumTest.EnumStringRequiredEnum#fromValue
org.openapitools.client.model.EnumTest.EnumIntegerEnum.serializer=org.openapitools.client.model.EnumTest.EnumIntegerEnum#serialize
org.openapitools.client.model.EnumTest.EnumIntegerEnum.deserializer=org.openapitools.client.model.EnumTest.EnumIntegerEnum#fromValue
org.openapitools.client.model.EnumTest.EnumNumberEnum.serializer=org.openapitools.client.model.EnumTest.EnumNumberEnum#serialize
org.openapitools.client.model.EnumTest.EnumNumberEnum.deserializer=org.openapitools.client.model.EnumTest.EnumNumberEnum#fromValue
org.openapitools.client.model.Order.StatusEnum.serializer=org.openapitools.client.model.Order.StatusEnum#serialize
org.openapitools.client.model.Order.StatusEnum.deserializer=org.openapitools.client.model.Order.StatusEnum#fromValue
org.openapitools.client.model.OuterEnum.serializer=org.openapitools.client.model.OuterEnum#serialize
org.openapitools.client.model.OuterEnum.deserializer=org.openapitools.client.model.OuterEnum#fromValue
org.openapitools.client.model.OuterEnumDefaultValue.serializer=org.openapitools.client.model.OuterEnumDefaultValue#serialize
org.openapitools.client.model.OuterEnumDefaultValue.deserializer=org.openapitools.client.model.OuterEnumDefaultValue#fromValue
org.openapitools.client.model.OuterEnumInteger.serializer=org.openapitools.client.model.OuterEnumInteger#serialize
org.openapitools.client.model.OuterEnumInteger.deserializer=org.openapitools.client.model.OuterEnumInteger#fromValue
org.openapitools.client.model.OuterEnumIntegerDefaultValue.serializer=org.openapitools.client.model.OuterEnumIntegerDefaultValue#serialize
org.openapitools.client.model.OuterEnumIntegerDefaultValue.deserializer=org.openapitools.client.model.OuterEnumIntegerDefaultValue#fromValue
org.openapitools.client.model.ParentWithNullable.TypeEnum.serializer=org.openapitools.client.model.ParentWithNullable.TypeEnum#serialize
org.openapitools.client.model.ParentWithNullable.TypeEnum.deserializer=org.openapitools.client.model.ParentWithNullable.TypeEnum#fromValue
org.openapitools.client.model.Pet.StatusEnum.serializer=org.openapitools.client.model.Pet.StatusEnum#serialize
org.openapitools.client.model.Pet.StatusEnum.deserializer=org.openapitools.client.model.Pet.StatusEnum#fromValue
org.openapitools.client.model.SingleRefType.serializer=org.openapitools.client.model.SingleRefType#serialize
org.openapitools.client.model.SingleRefType.deserializer=org.openapitools.client.model.SingleRefType#fromValue
java.time.LocalDate.serializer=org.openapitools.client.model.DataObjectMapper#serializeLocalDate
java.time.LocalDate.deserializer=java.time.LocalDate#parse
java.time.LocalDateTime.serializer=org.openapitools.client.model.DataObjectMapper#serializeLocalDateTime
java.time.LocalDateTime.deserializer=java.time.LocalDateTime#parse
java.time.OffsetDateTime.serializer=org.openapitools.client.model.DataObjectMapper#serializeOffsetDateTime
java.time.OffsetDateTime.deserializer=java.time.OffsetDateTime#parse
